### ISSUE TITLE
Adapter to http client

### ISSUE THREAD

**Issue by cloudson** [easytaxibr/newrelic#3]
I think that we need an adapter/interface to make the http requests instead of use a client itself. Currently , an application that uses guzzle 5 cannot use our library.
The requests are simple, so the adapters would be also simples.

**Comment by milhomem** [comment]
We can use https://github.com/guzzle/guzzle/blob/master/src/ClientInterface.php for now or just lower client requirement. In future we can use PSR7 interface for return a Request but it will loose power forcing user to add overhead code with He preferred httpclient.

**Comment by cloudson** [comment]
An internal interface like 

```php
<?php

namespace EasyTaxi\Newrelic;

interface HttpClient
{
    public function getUrlBase();
    public function post($, array $requestBody);
    public function get($uri);  // for the future, to work with the collector of the insights events. 
}
```

seems good to me. EasyTaxi\Newrelic could provide a first adapter of guzzle using the interface. 
My question is about the type hinting of these methods, what the post method should return? An internal response object? A boolean? A magic number - just kidding ? :confused:

**Comment by cloudson** [comment]
There is no reason to add support to other HTTP clients. So we will abandon this idea.
